[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pallet_rl"
version = "0.1.0"
description = "RL for Palletizing with Isaac Lab"
authors = [{name = "Riccardo4", email = "quartoriccardo@gmail.com"}]
dependencies = [
    "torch",
    "gymnasium",
    "warp-lang",
]

[tool.setuptools.packages.find]
include = ["pallet_rl*"]
